### ISSUE TITLE
AltPowerBar Buff Timers

### ISSUE THREAD

**Issue by Haleth** [oUF-wow/oUF#108]
Seems like a new interface element introduced in 4.3. It appears at some Darkmoon Faire games and shares a lot with the alt power bar, but both can be shown at the same time.

https://github.com/tekkub/wow-ui-source/blob/ptr/FrameXML/UnitPowerBarAlt.lua

http://img847.imageshack.us/img847/5107/wowscrnshot120511095336.jpg

**Comment by Rainrider** [comment]
Is the Darkmoon Fair the only thing that uses the couter bar system?

**Comment by Rainrider** [comment]
Please take a look at https://github.com/oUF-wow/oUF/tree/player-buff-timer for a WIP implementation of this. I opted for a separate element and pushed it unfinished in order to get feedback before the Darkmoon Fair ends.

To be yet included:
  - [ ] tooltips?
  - [ ] documentation
  - [ ] PostCreateTimer callback?
  - [ ] timer placement options (see TODOs in the code)

I only found the 3 darkmoon fair quests ("It's Hammer Time", "He Shoots, He Scores!" and "Tonk Commander") that use this. And only "Tonk Commander" does not have a normal buff to track the remaining time, so it's actually only one quest that "really" needs this.

Minimal layout implementation is simply `self.PlayerBuffTimers = {}`, where self is the player frame.

You could also use something like that if you prefer normal cooldown buttons over bars:
```lua
self.PlayerBuffTimers.CreateTimer = function(self, duration, expiration, auraID)
	local name, _, texture = GetSpellInfo(auraID)
	local button = CreateFrame("Button", nil, self)
	button:SetSize(32, 32)
	local cd = CreateFrame("Cooldown", nil, button, "CooldownFrameTemplate")
	cd:SetAllPoints()
	cd:SetReverse(true)
	local icon = button:CreateTexture(nil, "BORDER")
	icon:SetAllPoints()
	icon:SetTexture(texture)
	cd:SetCooldown(expiration - duration, duration)
	
	return button
end
```
