### ISSUE TITLE
Renaming DruidMana

### ISSUE THREAD

**Issue by p3lim** [oUF-wow/oUF#296]
This was brought up in #268, since the element is no longer exclusive to the druid class it should be renamed.

The two suggestions brought up then were "AdditionalPower" and "AlternatePower".
I would personally prefer the latter, but the name is (somewhat) occupied by the "AltPowerBar" element.

I've marked this down for the 1.7.0 milestone, as it's a breaking change.

**Comment by Sticklord** [comment]
I'll vote AlternatePowerBar or AlternatePower because that's what blizzard called theirs.

**Comment by p3lim** [comment]
> I'll vote AlternatePowerBar or AlternatePower because that's what blizzard called theirs.

Same reasoning for my preference as well, but we'll have two elements with similar names.

**Comment by Rainrider** [comment]
I would vote for _AditionalPowerBar_ as this is what Blizzard uses for associated stuff like **ADDITIONAL**_POWER_BAR_NAME and **ADDITIONAL**_POWER_BAR_INDEX.

I would vote against AlternatePowerBar since this is already properly used for the AltPowerBar and Blizzard uses it in _Unit**Alternate**PowerInfo_ and **ALTERNATE**_POWER_INDEX

Btw there is a [diffence between alternate and alternative](http://grammarist.com/usage/alternate-alternative/) but the way Blizzard uses it more like both, so AltPowerBar is just the perfect name imho.

**Comment by ls-** [comment]
I'm with @Rainrider on this one. Same reasons, and that's what I said in https://github.com/oUF-wow/oUF/pull/268#issuecomment-223030550.

**Comment by Blazeflack** [comment]
I vote for AdditionalPower as well.

**Comment by p3lim** [comment]
Votes in favor of "AdditionalPower", submitted #299.
