### ISSUE TITLE
A possible issue on The Coven of Shivarra (missing boss unit)

### ISSUE THREAD

**Issue by Blazeflack** [oUF-wow/oUF#405]
We received a report in ElvUI regarding the "The Coven of Shivarra" encounter. The player was not seeing the 3rd boss unitframe that should be available in that encounter. In different phases the 3rd boss is inactive, but casting stuff.

Reference: https://git.tukui.org/elvui/elvui/issues/226

The default UI shows 3 boss units in their boss frames. The player who reported it only sees 2, and he posted a screenshot from a streamer who also only sees 2.

Anyone able to confirm this?

**Comment by p3lim** [comment]
That is because we're using `RegisterUnitWatch` on every frame, while blizzard don't need to follow secure principles, and can therefore use other methods of verifying frame visibility.
Specific to this case is [this line](https://www.townlong-yak.com/framexml/live/TargetFrame.lua#108) in FrameXML/TargetFrame.lua, where the default boss frames show/hide based on `ShowBossFrameWhenUninteractable` in addition to `UnitExists`, which doesn't exist in the secure implementation ([FrameXML/SecureStateDriver.lua](https://www.townlong-yak.com/framexml/live/SecureStateDriver.lua#78)) where we only match by `UnitExists`.

Sadly, unfixable, poke Blizzard if you want a fix.

**Comment by Blazeflack** [comment]
Thanks for the explanation, I will inform the user about it.

**Comment by p3lim** [comment]
Got a confirmation that this is fixed already in an internal branch for the BfA expansion, and the representative from Blizzard was unsure if we're going to see it in 7.3.5 as they work on different branches of the UI/game.

**Comment by Blazeflack** [comment]
Thanks for the info.

**Comment by p3lim** [comment]
Also, my speculation of `ShowBossFrameWhenUninteractable` seems to have been incorrect, as it's "disabled" internally, it'll always return `true` :p
