### ISSUE TITLE
ClassPower backgrounds aren't shown

### ISSUE THREAD

**Issue by kavasto** [oUF-wow/oUF#426]
The statusbars are hidden if the power point is inactive, so the bg is never visible.

**Comment by Rainrider** [comment]
Don't parent your backgrounds to the bars then?

**Comment by kavasto** [comment]
I'm already working around this with PostUpdate. Just reporting here because it seems odd to use statusbars and then hide them instead of just relying on the value. Maybe it does make sense and I'm just missing something, though.

**Comment by zorker** [comment]
Afaik the classbar is only hidden when the current power value is 0. Which is especially useful for rogues. You only see the combo point class bar if you have any. I find it convenient that the classbar hides itself if you have no points in it.

I use my own classbar module in oUF_Simple because I use a different element approach but I do it the same way. When the current power value is 0 the bar will hide.

**Comment by Rainrider** [comment]
A persistent background is something we consider a decoration, which means it is up to the layout. The whole element historically used textures, but because of desto locks, we switched to statusbars for simplicity. We kept the behavior like it was with textures, where you had to layer and show your backgrounds a decorations yourself. The .bg option came to it because it is something common and oUF provides it for statusbars in other elements across the board.
