### ISSUE TITLE
Target, mouseover highlights for nameplates

### ISSUE THREAD

**Issue by d87** [oUF-wow/oUF#456]
Would be nice if oUF could handle internally things like target highlight, mouseover highlight, non-target transparency, while layout would only provide callbacks

Also, idk if this a bug or what, but nameplate callback doesn't fire for PLAYER_TARGET_CHANGED when player just drops target without picking a new one.

**Comment by ls-** [comment]
>Would be nice if oUF could handle internally things like target highlight, mouseover highlight, non-target transparency, while layout would only provide callbacks.

Nope, all of these are cosmetic features, they should be handled by the layout. What you're asking for is the same as asking us to implement always-on mouseover highlight for unit frames as a part of oUF core.

>Also, idk if this a bug or what, but nameplate callback doesn't fire for PLAYER_TARGET_CHANGED when player just drops target without picking a new one.

It's already fixed by #448, it'll be a part of upcoming oUF 9.0, it's already in the master branch.

**Comment by d87** [comment]
Ok, thanks
