### ISSUE TITLE
Is that possible to make ClassPower element support icicles?

### ISSUE THREAD

**Issue by Solor** [oUF-wow/oUF#485]
[Frost mage's icicles](https://www.wowhead.com/spell=76613) works just like class power, could you guys make class power element support it please 👶

**Comment by p3lim** [comment]
I think we've been asked this before, and our answer now is the same as then;

Right now, Blizzard doesn't consider the icicles system to be a proper class power but more like a "flare" to the sec, and because of this the icicles are only in the buff system (like other classes' powers were before too). The way the class power element is put together doesn't reasonably allow other APIs to work in there, such as the aura API, and trying to make it work regardless would be a nightmare.

So, our stance is this; until Blizzard treats icicles as a proper class power, we're not either.

Once Blizzard decides to treat icicles as a proper class power, we'll automatically have support for it.
Feel free to create your own element and distribute it with your layout, or as a separate plugin for oUF.
