### ISSUE TITLE
Not Hiding Blizzard Default Party Windows

### ISSUE THREAD

**Issue by Aideenwolf** [oUF-wow/oUF#628]
**Describe the bug**
oUF:DisableBlizzard('party')

config doesn't hide party windows anymore

**How to reproduce**
Add oUF:DisableBlizzard('party') to lua
join a party
Blizzard frames show - custom party/raid frames show

Doesn't matter if blizzard frames are set to "use Raid-Style Party frames" or not

**What did you expect?**
blizzard default party windows to be hidden

**Error report**
No error code in bug grabber - it kinda just ignores the code

**version**
oUF 11.0.0
Layout: Custom (not on WOWUI or Curse)

**Comment by ls-** [comment]
Ugh, weird... I'll look into it tomorrow >_>

**Comment by p3lim** [comment]
@Aideenwolf are you using the latest master from git? If not, which version are you using?

Also, do you have this option turned on from the Edit Mode?
![image](https://user-images.githubusercontent.com/26496/203634384-a65a84e1-d964-47db-a140-2d8a3372598d.png)

**Comment by Aideenwolf** [comment]
@p3lim I don't believe so - using the latest you can download off curse (release). Going to be honest didn't think to pull the latest off here.

That option is turned off currently.

**Comment by ls-** [comment]
We, well, I... usually assume that people who report stuff use our `master` branch rather than anything from addon sites. Anyway, if that's the case, what you're talking about has already been fixed in https://github.com/oUF-wow/oUF/commit/bbddb9d91c3e7facdd6d9cd464ee41b3f2a784b8 and https://github.com/oUF-wow/oUF/commit/30a3b33eda04b3670a639f1cee7d9eb2474e09de.
