### ISSUE TITLE
Castbar broken for vehicle during world quest

### ISSUE THREAD

**Issue by p3lim** [oUF-wow/oUF#676]
**Describe the bug**
During the world quest [A Dangerous Harvest](https://www.wowhead.com/quest=60872/a-dangerous-harvest) the [spell used for opening](https://www.wowhead.com/spell=3365/opening) the animacones is cast by the player and not the vehicle, thus the castbar is never shown.

**How to reproduce**
1. Pick up the world quest
2. Use the extra ability to turn into a moth
3. Loot an animacone

**What did you expect?**
Castbar showing

**Comment by p3lim** [comment]
I think an actual exclusion here is the best way to deal with it. Either by allowing the player casts to show while in a vehicle, or specifically for this spell. The former might pose a problem, but I'm unsure when that could be the case.

**Comment by p3lim** [comment]
Before the element revamp in #480 the unit checks used to also check for `realUnit`, maybe @ls
can give some insight into why this was removed.

**Comment by p3lim** [comment]
Hah, I was the one that added that support way back in 2014 with #230.

**Comment by ls-** [comment]
Huh? Am I missing something? 
![image](https://github.com/oUF-wow/oUF/assets/2725970/e1bf6b6f-eb44-4e52-86fd-6f4f405cdc9f)

**Comment by ls-** [comment]
Basically, unlike in the default UI where the player isn't shown in the pet frame we show both, the player is in the pet frame and the vehicle is in the player frame. They both have castbars in oUF, for instance, the moth has 2 abilities with 1s cast times, allergen cloud and dream dust in slots 1 and 2 respectively which do show up as castbars.

And here's the main difference. oUF shows castbars for those, but the default UI doesn't because after the default castbar was rewritten in DF it doesn't even switch units anymore, it's always locked to `"player"`, there's literally no vehicle castbar in the default UI anymore.

Iirc, the reason why I removed that `.realUnit` was because it often resulted in double castbars, like, both the pet and player/vehicle castbars would show up whenever something was cast by the player that's in the pet frame which isn't ideal, imho. For instance, here you can see both vehicle and pet/player castbars at the same time.

![image](https://github.com/oUF-wow/oUF/assets/2725970/129c7ead-e643-4b7d-9425-6390529137c0)
